#!/usr/bin/env php
<?php

if (file_exists(dirname(__FILE__).'/vendor/autoload.php')) {
    require_once dirname(__FILE__).'/vendor/autoload.php';
}

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (! is_writable(__DIR__.'/database.json')) {
    echo 'Database file not writable'."\n";
    die;
}

$app = (new \App\Kernel(require __DIR__.'/configs.php'));
